services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    depends_on:
      - stats-db
    networks:
        - ewm-network

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stats
    networks:
      - ewm-network

  ewm-service:
    build: main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    depends_on:
      - ewm-db
    networks:
      - ewm-network

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-main
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge
